services:
  temp-server:
    image: lrprojects/tempserver:1.0.0-SNAPSHOT
    restart: unless-stopped
    ports:
      - 8080:8080
    env_file:
      -  .env
    networks:
      - influxdb-network
      - postgresql-network
networks:
  influxdb-network:
    external: true
  postgresql-network:
    external: true
