openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http'
paths:
  /rest/v1/categories/:
    $ref: './methods/categories.yaml'
  /rest/v1/categories/{categoryId}:
    $ref: './methods/categoriesById.yaml'
  /rest/v1/sensors/{sensorId}:
    $ref: './methods/sensorsEntryById.yaml'
  /rest/v1/sensors:
    $ref: './methods/sensors.yaml'
  /rest/v1/sensors/{sensorId}/entry:
    $ref: './methods/sensorsById.yaml'
  /rest/v1/sensors/{sensorId}/graph:
    $ref: './methods/sensorsGraph.yaml'
  /rest/v1/types:
    $ref: './methods/sensorTypes.yaml'
  /rest/v1/types/{typeId}:
    $ref: './methods/sensorTypesById.yaml'